const data = [ 
  {name: 'Afghanistan', code: 'AF', alert: true }, 
  {name: 'Åland Islands', code: 'AX', alert: false },  
  {name: 'Albania', code: 'AL', alert: false }, 
  {name: 'Algeria', code: 'DZ', alert: false }, 
  {name: 'American Samoa', code: 'AS', alert: false }, 
  {name: 'AndorrA', code: 'AD', alert: false }, 
  {name: 'Angola', code: 'AO', alert: false }, 
  {name: 'Anguilla', code: 'AI', alert: false }, 
  {name: 'Antarctica', code: 'AQ', alert: false }, 
  {name: 'Antigua and Barbuda', code: 'AG', alert: false }, 
  {name: 'Argentina', code: 'AR', alert: false }, 
  {name: 'Armenia', code: 'AM', alert: false }, 
  {name: 'Aruba', code: 'AW', alert: false }, 
  {name: 'Australia', code: 'AU', alert: false }, 
  {name: 'Austria', code: 'AT', alert: false }, 
  {name: 'Azerbaijan', code: 'AZ', alert: false }, 
  {name: 'Bahamas', code: 'BS', alert: false }, 
  {name: 'Bahrain', code: 'BH', alert: false }, 
  {name: 'Bangladesh', code: 'BD', alert: false }, 
  {name: 'Barbados', code: 'BB', alert: false }, 
  {name: 'Belarus', code: 'BY', alert: false }, 
  {name: 'Belgium', code: 'BE', alert: false }, 
  {name: 'Belize', code: 'BZ', alert: false }, 
  {name: 'Benin', code: 'BJ', alert: false }, 
  {name: 'Bermuda', code: 'BM', alert: false }, 
  {name: 'Bhutan', code: 'BT', alert: false }, 
  {name: 'Bolivia', code: 'BO', alert: false }, 
  {name: 'Bosnia and Herzegovina', code: 'BA', alert: false }, 
  {name: 'Botswana', code: 'BW', alert: false }, 
  {name: 'Bouvet Island', code: 'BV', alert: false }, 
  {name: 'Brazil', code: 'BR', alert: false }, 
  {name: 'British Indian Ocean Territory', code: 'IO', alert: false },  
  {name: 'Brunei Darussalam', code: 'BN', alert: false }, 
  {name: 'Bulgaria', code: 'BG', alert: false }, 
  {name: 'Burkina Faso', code: 'BF', alert: false }, 
  {name: 'Burundi', code: 'BI', alert: false }, 
  {name: 'Cambodia', code: 'KH', alert: false }, 
  {name: 'Cameroon', code: 'CM', alert: false }, 
  {name: 'Canada', code: 'CA', alert: false }, 
  {name: 'Cape Verde', code: 'CV', alert: false }, 
  {name: 'Cayman Islands', code: 'KY', alert: false }, 
  {name: 'Central African Republic', code: 'CF', alert: false }, 
  {name: 'Chad', code: 'TD', alert: false }, 
  {name: 'Chile', code: 'CL', alert: false }, 
  {name: 'China', code: 'CN', alert: false }, 
  {name: 'Christmas Island', code: 'CX', alert: false }, 
  {name: 'Cocos (Keeling) Islands', code: 'CC', alert: false }, 
  {name: 'Colombia', code: 'CO', alert: false }, 
  {name: 'Comoros', code: 'KM', alert: false }, 
  {name: 'Congo', code: 'CG', alert: false }, 
  {name: 'Congo, The Democratic Republic of the', code: 'CD', alert: false },  
  {name: 'Cook Islands', code: 'CK', alert: false }, 
  {name: 'Costa Rica', code: 'CR', alert: false }, 
  {name: 'Cote D\'Ivoire', code: 'CI', alert: false }, 
  {name: 'Croatia', code: 'HR', alert: false }, 
  {name: 'Cuba', code: 'CU', alert: false }, 
  {name: 'Cyprus', code: 'CY', alert: false }, 
  {name: 'Czech Republic', code: 'CZ', alert: false }, 
  {name: 'Denmark', code: 'DK', alert: false }, 
  {name: 'Djibouti', code: 'DJ', alert: false }, 
  {name: 'Dominica', code: 'DM', alert: false }, 
  {name: 'Dominican Republic', code: 'DO', alert: false }, 
  {name: 'Ecuador', code: 'EC', alert: false }, 
  {name: 'Egypt', code: 'EG', alert: false }, 
  {name: 'El Salvador', code: 'SV', alert: false }, 
  {name: 'Equatorial Guinea', code: 'GQ', alert: false }, 
  {name: 'Eritrea', code: 'ER', alert: false }, 
  {name: 'Estonia', code: 'EE', alert: false }, 
  {name: 'Ethiopia', code: 'ET', alert: false }, 
  {name: 'Falkland Islands (Malvinas)', code: 'F', alert: false },  
  {name: 'Faroe Islands', code: 'FO', alert: false }, 
  {name: 'Fiji', code: 'FJ', alert: false }, 
  {name: 'Finland', code: 'FI', alert: false }, 
  {name: 'France', code: 'FR', alert: false }, 
  {name: 'French Guiana', code: 'GF', alert: false }, 
  {name: 'French Polynesia', code: 'PF', alert: false }, 
  {name: 'French Southern Territories', code: 'TF', alert: false }, 
  {name: 'Gabon', code: 'GA', alert: false }, 
  {name: 'Gambia', code: 'GM', alert: false }, 
  {name: 'Georgia', code: 'GE', alert: false }, 
  {name: 'Germany', code: 'DE', alert: false }, 
  {name: 'Ghana', code: 'GH', alert: false }, 
  {name: 'Gibraltar', code: 'GI', alert: false }, 
  {name: 'Greece', code: 'GR', alert: false }, 
  {name: 'Greenland', code: 'GL', alert: false }, 
  {name: 'Grenada', code: 'GD', alert: false }, 
  {name: 'Guadeloupe', code: 'GP', alert: false }, 
  {name: 'Guam', code: 'GU', alert: false }, 
  {name: 'Guatemala', code: 'GT', alert: false }, 
  {name: 'Guernsey', code: 'GG', alert: false }, 
  {name: 'Guinea', code: 'GN', alert: false }, 
  {name: 'Guinea-Bissau', code: 'GW', alert: false }, 
  {name: 'Guyana', code: 'GY', alert: false }, 
  {name: 'Haiti', code: 'HT', alert: false }, 
  {name: 'Heard Island and Mcdonald Islands', code: 'HM', alert: false },  
  {name: 'Holy See (Vatican City State)', code: 'VA', alert: false }, 
  {name: 'Honduras', code: 'HN', alert: false }, 
  {name: 'Hong Kong', code: 'HK', alert: false }, 
  {name: 'Hungary', code: 'HU', alert: false }, 
  {name: 'Iceland', code: 'IS', alert: false }, 
  {name: 'India', code: 'IN', alert: false }, 
  {name: 'Indonesia', code: 'ID', alert: false }, 
  {name: 'Iran, Islamic Republic Of', code: 'IR', alert: false },  
  {name: 'Iraq', code: 'IQ', alert: false }, 
  {name: 'Ireland', code: 'IE', alert: false }, 
  {name: 'Isle of Man', code: 'IM', alert: false }, 
  {name: 'Israel', code: 'IL', alert: false }, 
  {name: 'Italy', code: 'IT', alert: false }, 
  {name: 'Jamaica', code: 'JM', alert: false }, 
  {name: 'Japan', code: 'JP', alert: false }, 
  {name: 'Jersey', code: 'JE', alert: false }, 
  {name: 'Jordan', code: 'JO', alert: false }, 
  {name: 'Kazakhstan', code: 'KZ', alert: false }, 
  {name: 'Kenya', code: 'KE', alert: false }, 
  {name: 'Kiribati', code: 'KI', alert: false }, 
  {name: 'Korea, Democratic People\'S Republic of', code: 'KP', alert: false, shortName: 'Korea (DPR)' },  
  {name: 'Korea, Republic of', code: 'KR', alert: false }, 
  {name: 'Kuwait', code: 'KW', alert: false }, 
  {name: 'Kyrgyzstan', code: 'KG', alert: false }, 
  {name: 'Lao People\'S Democratic Republic', code: 'LA', alert: false },  
  {name: 'Latvia', code: 'LV', alert: false }, 
  {name: 'Lebanon', code: 'LB', alert: false }, 
  {name: 'Lesotho', code: 'LS', alert: false }, 
  {name: 'Liberia', code: 'LR', alert: false }, 
  {name: 'Libyan Arab Jamahiriya', code: 'LY', alert: false }, 
  {name: 'Liechtenstein', code: 'LI', alert: false }, 
  {name: 'Lithuania', code: 'LT', alert: false }, 
  {name: 'Luxembourg', code: 'LU', alert: false }, 
  {name: 'Macao', code: 'MO', alert: false }, 
  {name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK', alert: false },  
  {name: 'Madagascar', code: 'MG', alert: false }, 
  {name: 'Malawi', code: 'MW', alert: false }, 
  {name: 'Malaysia', code: 'MY', alert: false }, 
  {name: 'Maldives', code: 'MV', alert: false }, 
  {name: 'Mali', code: 'ML', alert: false }, 
  {name: 'Malta', code: 'MT', alert: false }, 
  {name: 'Marshall Islands', code: 'MH', alert: false }, 
  {name: 'Martinique', code: 'MQ', alert: false }, 
  {name: 'Mauritania', code: 'MR', alert: false }, 
  {name: 'Mauritius', code: 'MU', alert: false }, 
  {name: 'Mayotte', code: 'YT', alert: false }, 
  {name: 'Mexico', code: 'MX', alert: false }, 
  {name: 'Micronesia, Federated States of', code: 'FM', alert: false, shortName: 'Micronesia' },  
  {name: 'Moldova, Republic of', code: 'MD', alert: false }, 
  {name: 'Monaco', code: 'MC', alert: false }, 
  {name: 'Mongolia', code: 'MN', alert: false }, 
  {name: 'Montserrat', code: 'MS', alert: false }, 
  {name: 'Morocco', code: 'MA', alert: false }, 
  {name: 'Mozambique', code: 'MZ', alert: false }, 
  {name: 'Myanmar', code: 'MM', alert: false }, 
  {name: 'Namibia', code: 'NA', alert: false }, 
  {name: 'Nauru', code: 'NR', alert: false }, 
  {name: 'Nepal', code: 'NP', alert: false }, 
  {name: 'Netherlands', code: 'NL', alert: false }, 
  {name: 'Netherlands Antilles', code: 'AN', alert: false }, 
  {name: 'New Caledonia', code: 'NC', alert: false }, 
  {name: 'New Zealand', code: 'NZ', alert: false }, 
  {name: 'Nicaragua', code: 'NI', alert: false }, 
  {name: 'Niger', code: 'NE', alert: false }, 
  {name: 'Nigeria', code: 'NG', alert: false }, 
  {name: 'Niue', code: 'NU', alert: false }, 
  {name: 'Norfolk Island', code: 'NF', alert: false }, 
  {name: 'Northern Mariana Islands', code: 'MP', alert: false }, 
  {name: 'Norway', code: 'NO', alert: false }, 
  {name: 'Oman', code: 'OM', alert: false }, 
  {name: 'Pakistan', code: 'PK', alert: false }, 
  {name: 'Palau', code: 'PW', alert: false }, 
  {name: 'Palestinian Territory, Occupied', code: 'PS', alert: false }, 
  {name: 'Panama', code: 'PA', alert: false }, 
  {name: 'Papua New Guinea', code: 'PG', alert: false }, 
  {name: 'Paraguay', code: 'PY', alert: false }, 
  {name: 'Peru', code: 'PE', alert: false }, 
  {name: 'Philippines', code: 'PH', alert: false }, 
  {name: 'Pitcairn', code: 'PN', alert: false }, 
  {name: 'Poland', code: 'PL', alert: false }, 
  {name: 'Portugal', code: 'PT', alert: false }, 
  {name: 'Puerto Rico', code: 'PR', alert: false }, 
  {name: 'Qatar', code: 'QA', alert: false }, 
  {name: 'Reunion', code: 'RE', alert: false }, 
  {name: 'Romania', code: 'RO', alert: false }, 
  {name: 'Russian Federation', code: 'RU', alert: false }, 
  {name: 'RWANDA', code: 'RW', alert: false }, 
  {name: 'Saint Helena', code: 'SH', alert: false }, 
  {name: 'Saint Kitts and Nevis', code: 'KN', alert: false }, 
  {name: 'Saint Lucia', code: 'LC', alert: false }, 
  {name: 'Saint Pierre and Miquelon', code: 'PM', alert: false }, 
  {name: 'Saint Vincent and the Grenadines', code: 'VC', alert: false }, 
  {name: 'Samoa', code: 'WS', alert: false }, 
  {name: 'San Marino', code: 'SM', alert: false }, 
  {name: 'Sao Tome and Principe', code: 'ST', alert: false }, 
  {name: 'Saudi Arabia', code: 'SA', alert: false }, 
  {name: 'Senegal', code: 'SN', alert: false }, 
  {name: 'Serbia and Montenegro', code: 'CS', alert: false }, 
  {name: 'Seychelles', code: 'SC', alert: false }, 
  {name: 'Sierra Leone', code: 'SL', alert: false }, 
  {name: 'Singapore', code: 'SG', alert: false }, 
  {name: 'Slovakia', code: 'SK', alert: false }, 
  {name: 'Slovenia', code: 'SI', alert: false }, 
  {name: 'Solomon Islands', code: 'SB', alert: false }, 
  {name: 'Somalia', code: 'SO', alert: false }, 
  {name: 'South Africa', code: 'ZA', alert: false }, 
  {name: 'South Georgia and the South Sandwich Islands', code: 'GS', alert: false },  
  {name: 'Spain', code: 'ES', alert: false }, 
  {name: 'Sri Lanka', code: 'LK', alert: false }, 
  {name: 'Sudan', code: 'SD', alert: false }, 
  {name: 'Suriname', code: 'SR', alert: false }, 
  {name: 'Svalbard and Jan Mayen', code: 'SJ', alert: false }, 
  {name: 'Swaziland', code: 'SZ', alert: false }, 
  {name: 'Sweden', code: 'SE', alert: false }, 
  {name: 'Switzerland', code: 'CH', alert: false }, 
  {name: 'Syrian Arab Republic', code: 'SY', alert: false }, 
  {name: 'Taiwan, Province of China', code: 'TW', alert: false, shortName: 'Taiwan' }, 
  {name: 'Tajikistan', code: 'TJ', alert: false }, 
  {name: 'Tanzania, United Republic of', code: 'TZ', alert: false, shortName: 'Tanzania' },  
  {name: 'Thailand', code: 'TH', alert: false }, 
  {name: 'Timor-Leste', code: 'TL', alert: false }, 
  {name: 'Togo', code: 'TG', alert: false }, 
  {name: 'Tokelau', code: 'TK', alert: false }, 
  {name: 'Tonga', code: 'TO', alert: false }, 
  {name: 'Trinidad and Tobago', code: 'TT', alert: false }, 
  {name: 'Tunisia', code: 'TN', alert: false }, 
  {name: 'Turkey', code: 'TR', alert: false }, 
  {name: 'Turkmenistan', code: 'TM', alert: false }, 
  {name: 'Turks and Caicos Islands', code: 'TC', alert: false }, 
  {name: 'Tuvalu', code: 'TV', alert: false }, 
  {name: 'Uganda', code: 'UG', alert: false }, 
  {name: 'Ukraine', code: 'UA', alert: false }, 
  {name: 'United Arab Emirates', code: 'AE', alert: false, shortName: 'UAE'  }, 
  {name: 'United Kingdom', code: 'GB', alert: false, shortName: 'UK'  }, 
  {name: 'United States of America', code: 'US', alert: false, shortName: 'USA' }, 
  {name: 'United States Minor Outlying Islands', code: 'UM', alert: false },  
  {name: 'Uruguay', code: 'UY', alert: false }, 
  {name: 'Uzbekistan', code: 'UZ', alert: false }, 
  {name: 'Vanuatu', code: 'VU', alert: false }, 
  {name: 'Venezuela', code: 'VE', alert: false }, 
  {name: 'Viet Nam', code: 'VN', alert: false }, 
  {name: 'Virgin Islands, British', code: 'VG', alert: false }, 
  {name: 'Virgin Islands, U.S.', code: 'VI', alert: false }, 
  {name: 'Wallis and Futuna', code: 'WF', alert: false }, 
  {name: 'Western Sahara', code: 'EH', alert: false }, 
  {name: 'Yemen', code: 'YE', alert: false }, 
  {name: 'Zambia', code: 'ZM', alert: false }, 
  {name: 'Zimbabwe', code: 'ZW', alert: false }, 
];

export default data;

// Data will be fed into the combo on keypress via api that Brendan is building, due to business rules