---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manor-deployment
spec:
  selector:
    matchLabels:
      app: manor
  replicas: 1
  template:
    metadata:
      labels:
        app: manor
      annotations:
        fluentbit.io/exclude: "true"
    spec:
      containers:
      - name: manor
        image: quay.io/comparethemarketau/manor:$DOCKER_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 9493
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: manor-service
spec:
  selector:
    app: manor
  ports:
  - port: 9493
    protocol: TCP
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: manor-private-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "private"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: services.dev.comparethemarket.cloud
    http:
      paths:
      - path: /manor(/|$)(.*)
        backend:
          serviceName: manor-service
          servicePort: 9493
